// 一些常量
// 1小时 2小时 3小时 4小时 6小时 12小时 24小时
// 24小时 1天 1周 2周 3周 4周
// 1个月 2个月  3个月 4个月 6个月 12个月
// 1年

const SLOTS = {
    hour_1: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    hour_2: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上2小时",
        next: "下2小时",
        nextnext: "后一天",
        ratio: 4,
    },
    hour_3: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上3小时",
        next: "下3小时",
        nextnext: "后一天",
        ratio: 6,
    },
    hour_4: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上4小时",
        next: "下4小时",
        nextnext: "后一天",
        ratio: 8,
    },
    hour_6: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上6小时",
        next: "下6小时",
        nextnext: "后一天",
        ratio: 10,
    },
    hour_12: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上12小时",
        next: "下12小时",
        nextnext: "后一天",
        ratio: 2,
    },
    day_1: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    week_1: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    week_2: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    week_3: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    week_4: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    month_1: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    month_2: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    month_3: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },
    month_4: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },  month_6: {
        contentElementCount: "",
        prepre: "前一天",
        pre: "上一小时",
        next: "下一小时",
        nextnext: "后一天",
        ratio: 2,
    },  year: {
        contentElementCount: "",
        prepre: null,
        pre: "上一小时",
        next: "下一小时",
        nextnext: null,
        ratio: 2,
    }
};
